jteam/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:place_id>', views.cart_add, name='cart_add'),
    path('remove/<int:place_id>', views.cart_remove, name='cart_remove'),
]

jteam/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('create/', views.game_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.game_detail, name='detail'),
    path('join/', views.game_join, name='join'),
    path('', views.game_list, name='list'),
    path('ranking/', views.game_ranking, name='ranking'),
]

jteam/jteam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('games/', include('games.urls', namespace='games')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('location/', include('location.urls', namespace='location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jteam/games/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class Game(models.Model):
    """Модель, представляющая игру."""
    SPORTS = (
        ('football', 'футбол'),
        ('tennis', 'теннис'),
        ('bowling', 'боулинг'),
        ('beach volleyball', 'пляжный волейбол'),
        ('volleyball', 'волейбол'),
        ('ice hockey', 'хоккей на льду'),
        ('chess', 'шахматы'),
    )
    SPORT_ICONS = {
        'football': 'football-icon.png',
        'tennis': 'tennis-icon.png',
        'ice hockey': 'hockey-icon.png',
        # Добавьте другие виды спорта и соответствующие иконки
    }

    CHOICES = (("open", "Open"), ("started", "Started"), ("finished", "Finished"))

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='user_games_created',
                             on_delete=models.CASCADE)
    sport = models.CharField(max_length=255, choices=SPORTS)
    place = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=timezone.now)
    duration = models.DurationField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    max_players = models.PositiveIntegerField(default=2)
    joined_players = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                            related_name='joined_games',
                                            blank=True)
    status = models.CharField(max_length=255,
                              choices=CHOICES, default='Open')
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='images/%Y/%m/%d',
                              blank=True)

    class Meta:
        """
        Мета-класс для модели Game.

        Определяет:
            * `verbose_name`: Отображение названия модели
             в единственном числе (админ-панель и т.д.).
            * `verbose_name_plural`: Отображение названия модели
             во множественном числе (админ-панель и т.д.).
            * `indexes`: Индексы для полей модели для улучшения производительности запросов.
            * `ordering`: Порядок по умолчанию для объектов модели при их получении.
        """
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'
        indexes = [
            models.Index(fields=['created_at']),
        ]
        ordering = ['created_at']

    def __str__(self):
        return f'{self.sport} {self.date} {self.start_time} {self.place}'

    def save(self, *args, **kwargs):
        """Сохраняет игру.
        Если слаг не задан, генерирует его из названия вида спорта, даты и места.
        """
        if not self.slug:
            self.slug = slugify(self.sport, allow_unicode=True) + '-' + \
                        slugify(self.date, allow_unicode=True) + '-' + \
                        slugify(self.created_at, allow_unicode=True) + '-' + \
                        slugify(self.user, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Возвращает URL-адрес страницы детального отображения игры."""
        return reverse('games:detail', args=[self.id, self.slug])

    # ...Можно добавить проверку на существование игры перед генерацией URL-адреса.

    # models.py:

    # Подсчет оставшихся слотов.
    # Проверка доступности игры.
    # views.py:
    # Обработка запроса на вступление в игру.
    # Отображение списка доступных игр.

jteam/games/forms.py
from django import forms
from django.forms import Select, TextInput, NumberInput, Textarea, ClearableFileInput

from .models import Game


class GameCreateForm(forms.ModelForm):
    """
    Форма создания игры.

    """

    class Meta:
        model = Game
        fields = [
            'sport',
            'place',
            'date',
            'start_time',
            'duration',
            'max_players',
            'price',
            'description',
            'image',
        ]
        labels = {
            'sport': 'Вид спорта',
            'place': 'Место игры',
            'date': 'Дата игры',
            'start_time': 'Время начала игры',
            'duration': 'Продолжительность',
            'max_players': 'Количество игроков',
            'price': 'Цена игры',
            'description': 'Описание',
            'image': 'Обложка',
        }

        widgets = {
            'sport': Select(attrs={'class': 'form-control form-control-width',
                                   'style': 'background-color: #f8f9fa; border-radius: 5px;',
                                   }),
            'place': TextInput(attrs={'class': 'form-control form-control-width',
                                      'style': 'background-color: #f8f9fa; border-radius: 5px;',
                                      }),
            'max_players': NumberInput(attrs={'class': 'form-control form-control-width',
                                              'step': '1',
                                              'style': 'background-color: #f8f9fa; border-radius: 5px;',
                                              }),
            'description': Textarea(attrs={'cols': 30,
                                           'rows': 3,
                                           'class': 'form-control form-control-width',
                                           'type': 'text',
                                           'placeholder': 'Опишите например: есть душевые, есть парковочные места',
                                           'aria-label': 'default input example',
                                           'style': 'background-color: #f8f9fa; border-radius: 5px;'
                                           }),
            'price': NumberInput(attrs={'step': '10',
                                        'class': 'form-control form-control-width',
                                        'style': 'background-color: #f8f9fa; border-radius: 5px;'
                                        }),
            'duration': TextInput(attrs={'placeholder': 'HH:MM',
                                         'type': 'time',
                                         'class': 'form-control form-control-width',
                                         'style': 'background-color: #f8f9fa; border-radius: 5px;'}),
            'date': TextInput(attrs={'placeholder': 'HH:MM',
                                         'type': 'date',
                                         'class': 'form-control form-control-width',
                                         'style': 'background-color: #f8f9fa; border-radius: 5px;'}),
            'start_time': TextInput(attrs={'placeholder': 'HH:MM',
                                         'type': 'time',
                                         'class': 'form-control form-control-width',
                                         'style': 'background-color: #f8f9fa; border-radius: 5px;'}),
            'image': ClearableFileInput(attrs={
                'class': 'form-control form-control-width',
                'style': 'background-color: #f8f9fa; border-radius: 5px;',
            })
        }

jteam/games/views.py
import redis
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.http import require_POST
from actions.utils import create_action

from .forms import GameCreateForm
from .models import Game


def validate_date(value):
    if value < timezone.now().date():
        raise ValidationError('Дата не может быть в прошлом.')


def validate_time(value):
    now = timezone.now()
    if value < now.time() or (value == now.time() and now.date() > value.date()):
        raise ValidationError('Время не может быть в прошлом.')

@login_required
def game_create(request):
    if request.method == 'POST':
        form = GameCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_game = form.save(commit=False)
            new_game.user = request.user
            new_game.save()
            create_action(request.user, 'создал(а) игру', new_game)
            messages.success(request,
                             'Игра успешно создана')
            return redirect(new_game.get_absolute_url())
    else:
        form = GameCreateForm()
    return render(request,
                  'games/game/create.html',
                  {'section': 'games',
                   'form': form})


def game_detail(request, id, slug):
    game = get_object_or_404(Game, id=id, slug=slug)
    # увеличить общее число просмотров игр на 1
    # пространство имен формат object-type:id:field
    total_views = r.incr(f'game:{game.id}:views')
    # увеличить рейтинг игр на 1
    # создаём сортированное множество
    r.zincrby('game_ranking', 1, game.id)
    return render(request,
                  'games/game/detail.html',
                  {'section': 'games',
                   'game': game,
                   'total_views': total_views})

@login_required
def game_list(request):
    """Выводит постраничный список игр"""
    games = Game.objects.all()
    paginator = Paginator(games, 12)
    page = request.GET.get('page')
    games_only = request.GET.get('games_only')
    try:
        games = paginator.page(page)
    except PageNotAnInteger:
        # Если page_number не целое число, то
        # выдать первую страницу
        games = paginator.page(1)
    except EmptyPage:
        if games_only:
            # Если AJAX-запрос и страница вне диапазона,
            # то вернуть пустую страницу
            return HttpResponse('')
        # Если страница вне диапазона,
        # то вернуть последнюю страницу результатов
        games = paginator.page(paginator.num_pages)
    if games_only:
        return render(request,
                      'games/game/list_games.html',
                      {"section": 'games',
                       'games': games})
    return render(request,
                  'games/game/list.html',
                  {"section": 'games',
                   'games': games})

# Не дает пользователям, не вошедшим в систему, обращаться к этому представлению.
# Этому представлению разрешаются запросы только методом POST.
@login_required
@require_POST
def game_join(request):
    """ Представление, которое позволяет пользователям присоед./выйти из игры"""
    game_id = request.POST.get('id')
    # action берется из атрибута action="/submit", если его нет, то есть ещё варианты.
    action = request.POST.get('action')
    if game_id and action:
        try:
            game = Game.objects.get(id=game_id)
            if action == 'join':
                # Проверяет лимит присоединений
                if game.joined_players.count() >= game.max_players:
                    messages.error(request,
                                     'Максимальное количество игроков достигнуто.')
                    return JsonResponse({'status': 'error',
                                         'message': 'Максимальное количество игроков достигнуто.'})
                # Добавление пользователя в игру
                game.joined_players.add(request.user)
                create_action(request.user, 'присоединился(ась) к игре', game)
            else:
                game.joined_players.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Game.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


# соединить с redis
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def game_ranking(request):

    # получить словарь рейтинга игр
    # Для получения элементов сортированного множества game_ranking исползьуеться zrange()
    game_ranking = r.zrange('game_ranking', 0, -1, desc=True)[:10]
    game_ranking_ids = [int(id) for id in game_ranking]

    # получить наиболее просматриваемые изображения
    most_viewed = list(Game. objects.filter(
                            id__in=game_ranking_ids))
    most_viewed.sort(key=lambda x: game_ranking_ids.index(x.id))
    return render(request,
                  'games/game/ranking.html',
                  {'section': 'games',
                   'most_viewed': most_viewed})

jteam/games/templates/games/game/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Создать игру {% endblock %}

{% block content %}
  <h1> Создать игру </h1>
    <p>* Поля со звёздочкой являются обязательными</p>
    <form method="post">
        <div class="createGame">
            {% csrf_token %}
            {{ form|crispy }}
        </div>
        <div class="createGameButton">
            <input class="btn btn-primary" type="submit" value="Создать игру">
        </div>
    </form>
{% endblock %}

jteam/games/templates/games/game/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ game.sport }} | {{ user.username }}{% endblock %}

{% block content %}

    <h1>{{ game.get_sport_display }}
        <p>{% if game.image %}
          {% thumbnail game.image "100x100" crop="100%" as cover %}
            <img src="{{ cover.url }}" class="item-img">
        {% endif %}
        </p>
    </h1>
        <p>{{ user.first_name }} - {{ user.email }}</p>
        <p>
            <i class="fas fa-calendar"></i> {{ game.date }}&nbsp;&nbsp;&nbsp;
            <i class="fas fa-clock"></i> {{ game.start_time }}&nbsp;&nbsp;&nbsp;
            <i class="fas fa-map-marker"></i> {{ game.place }}
        </p>
    <p>{{ game.description }}</p>

    <p>
      <i class="fas fa-coins"></i> {{ game.price }}
    </p>

    {% with total_jones=game.joined_players.count joined_players=game.joined_players.all %}
    <div>
        <p><i class="fas fa-users"></i>
        <span class="count">
            {{ total_jones }} / {{ game.max_players }}
        </span></p>
        <p> <i class="fas fa-eye"></i>
        <span class="count">
            {{ total_views }} view{{ total_views|pluralize }}
        </span></p>
        <a href="#" data-id="{{ game.id }}"
           data-action="{% if request.user in joined_players %}un{% endif %}join"
           data-max-players="{{ game.max_players }}"
           class="like button">
            {% if request.user not in joined_players %}
                Join
            {% else %}
                Unjoin
            {% endif %}
        </a>
    </div>
        <div class="image-likes">
            {% for user in joined_players %}
                <div>
                    {% if user.profile.photo %}
                        {% thumbnail user.profile.photo "80x80" crop="100%" as im %}
                        <img src="{{ im.url }}" class="item-img">
                    {% endif %}
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody players joined
            {% endfor %}
        </div>

    {% endwith %}
{% endblock %}

{% block domready %}
    const url = '{% url "games:join" %}';

    var options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
        mode: 'same-origin'
    }

    document.querySelector('a.button')
            .addEventListener('click', function(e){
        e.preventDefault();
        var joinButton = this;

        var gameId = joinButton.dataset.id;
        var action = joinButton.dataset.action;

    // добавить тело запроса
    var formData = new FormData();
    formData.append('id', joinButton.dataset.id);
    formData.append('action', joinButton.dataset.action);
    options['body'] = formData;

    // отправить HTTP-запрос
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
        if (data['status'] ==='ok')
        {
            var previousAction = joinButton.dataset.action;

            // переключить текст кнопки и атрибут data-action
            var action = previousAction === 'join' ? 'unjoin' : 'join';
            joinButton.dataset.action = action;
            joinButton.innerHTML = action;

            // обновить количество присоединений игроков
            var joinCount = document.querySelector('span.count');
            var totalJoins = parseInt(joinCount.innerHTML);
            var maxPlayers = parseInt(joinButton.dataset.maxPlayers);
            joinCount.innerHTML = previousAction === 'join' ? totalJoins + 1 + ' / ' + maxPlayers : totalJoins - 1 + ' / ' + maxPlayers;
        }
      })
    });
{% endblock %}

jteam/games/templates/games/game/list.html
{% extends "base.html" %}

{% block title %}Games JTeam{% endblock %}

{% block content %}
    <h1>Список доступных игр</h1>
    <p>Выбери игру из списка ниже или создай сам <a href="{% url 'games:create' %}" class="btn btn-primary">Создать игру</a></p>

<!--         id game-list используется для обработки в JavaScript-->
        <div id="game-list">
            {% include "games/game/list_games.html" %}
        </div>

<!--    {% include "pagination.html" with page=games %}-->
{% endblock %}

{% block domready %}
<!--Прокрутка страницы вниз, чтобы загрузить дополнительные страницы-->
 var page = 1;
  var emptyPage = false;
  var blockRequest = false;

  window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true;
      page += 1;

      fetch('?games_only=1&page=' + page)
      .then(response => response.text())
      .then(html => {
        if (html === '') {
          emptyPage = true;
        }
        else {
          var gameList = document.getElementById('game-list');
          gameList.insertAdjacentHTML('beforeEnd', html);
          blockRequest = false;
        }
      })
    }
  });

  // Launch scroll event
  const scrollEvent = new Event('scroll');
  window.dispatchEvent(scrollEvent);
{% endblock %}

jteam/games/templates/games/game/list_games.html
<div class="row row-cols-1 g-4">
{% for game in games %}
    <div class="col">
            <div class="card">
              <div class="card-body">
                <div class="info">
                    <a href="{{ game.get_absolute_url }}">
                        {{ game.get_sport_display }}&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-calendar"></i> &nbsp; {{ game.date }}&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-clock"></i> {{ game.start_time }}&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-map-marker"></i> &nbsp; {{ game.place }}
                    </a>
                </div>
              </div>
            </div>
    </div>
{% endfor %}
</div>

jteam/games/templates/games/game/ranking.html
{% extends "base.html" %}
{% block title %}Рейтинг игр{% endblock %}
{% block content %}
 <h1>Рейтинг игр</h1>
 <ol>
     {% for game in most_viewed %}
        <li>
            <a href="{{ game.get_absolute_url }}">
                <p class="underline">{{ game.get_sport_display }} - {{ game.user.first_name }}</p>
            </a>
            <p>
                <i class="fas fa-calendar"></i> {{ game.date }}&nbsp;&nbsp;&nbsp;
                <i class="fas fa-clock"></i> {{ game.start_time }}&nbsp;&nbsp;&nbsp;
                <i class="fas fa-map-marker"></i> {{ game.place }}
            </p>
        </li>
     {% endfor %}
 </ol>
{% endblock %}