jteam/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('search/', views.account_search, name='account_search'),
    # path('results/', views.search_results, name='search_results'),
]

jteam/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:place_id>', views.cart_add, name='cart_add'),
    path('remove/<int:place_id>', views.cart_remove, name='cart_remove'),
]

jteam/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('create/', views.game_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.game_detail, name='detail'),
    path('join/', views.game_join, name='join'),
    path('', views.game_list, name='list'),
    path('ranking/', views.game_ranking, name='ranking'),
]

jteam/jteam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('games/', include('games.urls', namespace='games')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('location/', include('location.urls', namespace='location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jteam/account/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='profile',
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True,
                              default='default-profile-user.jpg',)

    def __str__(self):
        return f'Profile of {self.user.username}'

    def get_absolute_url(self):
        return reverse('user_detail', args=[str(self.id)])


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User',
                                  related_name='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User',
                                related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return f'{self.user_from} joined {self.user_to}'


# Добавление поле в User динамически
user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self',
                                               through=Contact,
                                               related_name='followers',
                                               symmetrical=False))

jteam/account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use.')
        return data

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id)\
                        .filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Email already in use.')
        return data

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']


# возможность вводить поисковые запросы
class SearchForm(forms.Form):
    query = forms.CharField(label='',
                            max_length=100,
                            widget=forms.TextInput(attrs={
                                'placeholder': 'Введите имя игрока',
                                'class': 'form-control form-control-width',
                                'style': 'background-color: #f8f9fa; border-radius: 5px;',
                            }))

jteam/account/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
from .forms import LoginForm, UserRegistrationForm, \
    UserEditForm, ProfileEditForm, SearchForm
from .models import Profile, Contact
from actions.utils import create_action
from actions.models import Action
from .service import search_users


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    # По умолчанию показать все действия
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id',
                                                       flat=True)
    if following_ids:
        # Если пользователь подписан на других, то извлечь только их действия
        # Здесь user_id__in используется для фильтрации объектов по значению поля user_id.
        # Например, MyModel.objects.filter(user_id__in=[1, 2, 3]) вернет объекты,
        # у которых user_id равен 1, 2 или 3.
        actions = actions.filter(user_id__in=following_ids)

    # В Django, двойное подчеркивание (__) используется для обращения к связанным полям
    # в моделях. В данном случае, user__profile означает, что мы обращаемся к полю profile,
    # связанному с полем user в модели.
    actions = actions.select_related('user', 'user__profile')[:10]\
                     .prefetch_related('target')[:10]
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'actions': actions})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object,
            # but don't save it yet.
            new_user = user_form.save(commit=False)
            # set the selected password
            new_user.set_password(user_form.cleaned_data['password'])

            # save the object User
            new_user.save()
            # Создать профиль пользователя
            Profile.objects.create(user=new_user)
            create_action(new_user, 'создал(а) учётную запись')
            return render(request, 'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html',
                  {'user_form': user_form})


@login_required
def edit(request):
    """Обрабатывает редактирование профиля пользователя."""
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated ', 'successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
                                    instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request,
                  'account/user/list.html',
                  {'section': 'people',
                   'users': users,
                   'form': SearchForm()})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User,
                             username=username,
                             is_active=True)
    return render(request,
                  'account/user/detail.html',
                  {'section': 'people',
                   'user': user})


@require_POST
@login_required
def user_follow(request):
    """Выводит страницу пользователя или 404, если не найден."""
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(
                   user_from=request.user,
                   user_to=user)
                create_action(request.user, 'подписался(ась) на', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'error'})
    return JsonResponse({'status': 'error'})


def account_search(request):
    """ Поиск игрока по нику, имени и фамилии"""
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = search_users(query)
    return render(request,
                  'account/user/search_results.html',
                  {'form': form,
                   'query': query,
                   'results': results})

jteam/account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" href="{% static 'image/jpeg/logo_jteam_ico.ico' %}" type="image/x-icon"/>
    <!-- icons with fontawesomefree -->
    <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
    <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
    <!-- end icons with fontawesomefree -->

</head>
<body>
    <div id="header">
        <span class="logo"><a href="{% url 'dashboard' %}">JTeam</a></span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %} class='selected'{% endif %}>
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li {% if section == "games" %} class="selected"{% endif %}>
                    <a href="{% url 'games:list' %}">Список игр</a>
                </li>
                <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="{% url 'user_list' %}">Игроки</a>
                </li>
                <li {% if section == "location" %} class="selected"{% endif %}>
                    <a href="{% url 'location:list' %}">Список мест</a>
                </li>
                <li {% if section == "cart" %} class="selected"{% endif %}>
                      {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                          <a href="{% url 'cart:cart_detail' %}">
                              <i class="fas fa-shopping-cart"></i>
                              {{ total_items }} place{{ total_items|pluralize }},
                              ₽{{ cart.get_total_price }}
                          </a>
                        {% else %}
                            <a href="{% url 'cart:cart_detail' %}">
                           <i class="fas fa-shopping-cart"></i> 0 place, ₽0
                            </a>
                        {% endif %}
                      {% endwith %}
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name|default:request.user.username }},
<!--                ссылка не работала пришлось поменять на форму-->
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">выйти</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- скрипт для закладки картинки с других сайтов -->
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var closeButtons = document.querySelectorAll('.close');

        closeButtons.forEach(function(button) {
            button.addEventListener('click', function(event) {
                event.preventDefault();
                var message = this.parentNode;
                message.style.display = 'none';
            });
        });
    });
    </script>

    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <!-- Загрузка JavaScript в DOM -->
    <script>
        const csrftoken = Cookies.get('csrftoken');
        document.addEventListener('DOMContentLoaded', (event) => {
            // DOM загружена
            {% block domready %}
            {% endblock %}
        })
    </script>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>