jteam/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:place_id>', views.cart_add, name='cart_add'),
    path('remove/<int:place_id>', views.cart_remove, name='cart_remove'),
]

jteam/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('create/', views.game_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.game_detail, name='detail'),
    path('join/', views.game_join, name='join'),
    path('', views.game_list, name='list'),
    path('ranking/', views.game_ranking, name='ranking'),
]

jteam/jteam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('games/', include('games.urls', namespace='games')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('location/', include('location.urls', namespace='location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jteam/orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

jteam/cart/models.py
from django.db import models

# Create your models here.

jteam/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

jteam/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from location.models import Place


@require_POST
def cart_add(request, place_id):
    cart = Cart(request)
    place = get_object_or_404(Place, id=place_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(place=place,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, place_id):
    cart = Cart(request)
    place = get_object_or_404(Place, id=place_id)
    cart.remove(place)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

jteam/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Ваша корзина
{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Place</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with place=item.place %}
                    <tr>
                        <td>
                            <a href="{{ place.get_absolute_url }}">
                                <img src="{% if place.image %}{{ place.image.url }}
                                {% else %}{% static 'image/png/no_image.png' %}{% endif %}"
                                     alt="{{ place.name }}">
                            </a>
                        </td>
                        <td>{{ place.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <form action="{% url 'cart:cart_remove' place.id %}"
                                  method="post">
                                <input type="submit" value="Remove">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">₽{{ item.price }}</td>
                        <td class="num">₽{{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">₽{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'location:list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">
            Checkout
        </a>
    </p>
{% endblock %}