jteam/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:place_id>', views.cart_add, name='cart_add'),
    path('remove/<int:place_id>', views.cart_remove, name='cart_remove'),
]

jteam/jteam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('games/', include('games.urls', namespace='games')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('location/', include('location.urls', namespace='location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jteam/location/urls.py
from django.urls import path
from . import views

app_name = 'location'

urlpatterns = [
    path('', views.place_list, name='list'),
    path('list/<slug:city_slug>/', views.place_list,
         name='place_list_by_city'),
    path('place_detail/<int:id>/<slug:slug>/', views.place_detail,
         name='place_detail'),
]

jteam/location/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
     name = models.CharField(max_length=200)
     slug = models.SlugField(max_length=200,
                             unique=True)
     class Meta:
         ordering = ['name']
         indexes = [
             models.Index(fields=['name']),
         ]
         verbose_name = 'city'
         verbose_name_plural = 'cities'

     def __str__(self):
        return self.name

     def get_absolute_url(self):
         return reverse('location:place_list_by_city',
                        args=[self.slug])


class Place(models.Model):
    city = models.ForeignKey(City,
                             related_name='places',
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='places/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('location:place_detail',
                       args=[self.id, self.slug])

jteam/location/views.py
from django.shortcuts import get_object_or_404, render

from .models import City, Place
from cart.forms import CartAddProductForm


def place_list(request, city_slug=None):
    city = None
    cities = City.objects.all()
    places = Place.objects.filter(available=True)
    if city_slug:
        city = get_object_or_404(City,
                                 slug=city_slug)
        places = places.filter(city=city)
    return render(request,
                  'place/list.html',
                  {'city': city,
                   'cities': cities,
                   'places': places})

def place_detail(request, id, slug):
    place = get_object_or_404(Place,
                              id=id,
                              slug=slug,
                              available=True)
    cart_place_form = CartAddProductForm()
    return render(request,
                  'place/detail.html',
                  {'place': place,
                   'cart_place_form': cart_place_form})

jteam/location/templates/place/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
 {{ place.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if place.image %}{{ place.image.url }}{% else %}
        {% static 'image/png/no_image.png' %}{% endif %}">
        <h1>{{ place.name }}</h1>
        <h2>
            <a href="{{ place.city.get_absolute_url }}">
                {{ place.city }}
            </a>
        </h2>
        <p class="price">₽{{ place.price }}</p>
        <form action="{% url 'cart:cart_add' place.id %}" method="post">
            {{ cart_place_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ place.description|linebreaks }}
    </div>
{% endblock %}

jteam/location/templates/place/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% if city %}{{ city.name }}{% else %}Places{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Cities</h3>
        <ul>
            <li {% if not city %}class="selected"{% endif %}>
              <a href="{% url 'location:list' %}">All</a>
            </li>
            {% for c in cities %}
              <li {% if city.slug == c.slug %}class="selected"
              {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
      <h1>{% if city %}{{ city.name }}{% else %}Places
      {% endif %}</h1>
      {% for place in places %}
        <div class="item">
            <a href="{{ place.get_absolute_url }}">
                <img src="{% if place.image %}{{ place.image.url }}
                          {% else %}{% static 'image/png/no_image.png' %}{% endif %}">
            </a>
            <a href="{{ place.get_absolute_url }}">{{ place.name }}</a>
            <br>
            ₽{{ place.price }}
        </div>
      {% endfor %}
    </div>
{% endblock %}